version: '3'

services:
    microservice-1:
        build: ./microservice-1
        volumes:
            - ./microservice-1/app.js:/usr/src/app/app.js
        expose:
            - '8080'

    microservice-2:
        build: ./microservice-2
        volumes:
            - ./microservice-2:/usr/src/app
        expose:
            - '8080'

    website:
        image: nginx:1.17-alpine
        volumes: 
            - ./static-file-server/static-content:/usr/share/nginx/html
            - ./static-file-server/nginx-config/reverse-proxy.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
        depends_on: 
            - microservice-1
            - microservice-2