apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
        - name: service1
          image: {{ .Values.werf.image.service1 }}
          ports:
            - containerPort: 80
        - name: service2
          image: {{ .Values.werf.image.service2 }}
          ports:
            - containerPort: 80
        - name: static-file-server
          image: {{ .Values.werf.image.service3 }}
          ports:
            - containerPort: 80